use std::{error::Error, result::Result};

fn main() -> Result<(), Box<dyn Error>> {
    Ok(())
}
